name: Coding Standards

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    name: CS Fixer
    steps:
      - uses: actions/checkout@v2

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php_cs.dist --dry-run --stop-on-violation --using-cache=no --verbose
